### PR TITLE
Assignment complete

### PR DESCRIPTION
**Pull request by lsimmons1832**

### CODE REVIEW

**Comment by lsimmons1832** [comment]
@devoisaurus

**Comment by devoisaurus** [comment]
You've got the link color changing on hover, but the background for the entire list changes on hover, rather than each individual item. Maybe look into ways to differentiate between the elements for more individualized styling.

**Comment by lsimmons1832** [comment]
@devoisaurus

**Comment by devoisaurus** [comment]
Looks like you have the whole element growing when one is clicked instead of each individual element

**Pull request merged**
